apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "https://kickstarter.saas.appdynamics.com"
  account: "kickstarter"
  appName: "local_teastore"
  serviceAccountName: appdynamics-cluster-agent
  image: "docker.io/appdynamics/cluster-agent:20.5.0"
  nsToMonitor: [appdynamics,default,teastore]
  instrumentationMethod: Env
  nsToInstrumentRegex: stage|dev|teastore
  appNameStrategy: manual
  defaultAppName: local_teastore
  instrumentationRules:
    - namespaceRegex: teastore
      appName: local_teaStore
  resourcesToInstrument: [Deployment,StatefulSet]
  imageInfo:
    java:
      image: "docker.io/appdynamics/java-agent:latest"
      agentMountPath: /opt/appdynamics
      imagePullPolicy: Always
  netvizInfo:
    bciEnabled: true
    port: 3892
